# Change these first
owner: imagix-tech # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://imagix.tech
  - name: Webmail
    url: https://webmail.imagix.tech
  - name: Suporte
    url: https://suporte.imagix.tech    
  - name: ODIN (Homologation)    
    url: https://hmg-app.demo.odin.imagix.tech
  - name: ODIN API (Homologation)    
    url: http://hmg-api.demo.odin.imagix.tech/healthz   
  - name: BIFROST (Homologation)    
    url: https://hmg-app.demo.bifrost.imagix.tech    
  - name: BIFROST API (Homologation)    
    url: https://hmg-api.demo.bifrost.imagix.tech/health
  - name: ODIN App PoC
    url: $APP_ODIN_POC
  - name: BIFROST App PoC
    url: $APP_BIFROST_POC    
  - name: DNS 1
    check: "tcp-ping"
    url: dns1.xaonix.com
    port: 53
  - name: DNS 2
    check: "tcp-ping"
    url: dns2.xaonix.com
    port: 53
  - name: DNS 3
    check: "tcp-ping"
    url: dns3.uni5.net
    port: 53
  - name: DNS 4
    check: "tcp-ping"
    url: dns4.uni5.net
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.imagix.tech
  # baseUrl: /
  theme: night
  logoUrl: https://raw.githubusercontent.com/imagix-tech/status/master/imagix.svg
  favicon: https://raw.githubusercontent.com/imagix-tech/status/master/favicon.ico
  faviconSvg: https://raw.githubusercontent.com/imagix-tech/status/master/favicon.svg
  name: Status Page
  introTitle: Welcome to the IMAGIX Service Status Page
  introMessage: Here, you will find real-time updates on any ongoing issues, scheduled maintenance, and overall system performance.   
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://imagix.tech

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
