owner: imagix-tech
repo: status

sites:
  - name: Website
    url: https://imagix.tech
  - name: Dev
    url: http://dev.imagix.tech
  - name: DNS 1
    check: "tcp-ping"
    url: dns1.xaonix.com
    port: 53
  - name: DNS 2
    check: "tcp-ping"
    url: dns2.xaonix.com
    port: 53 
  - name: DNS 3
    check: "tcp-ping"
    url: 177.12.162.2
    port: 53
  - name: DNS 4
    check: "tcp-ping"
    url: 177.12.162.3
    port: 53
    
status-website:
  favicon: https://raw.githubusercontent.com/imagix-tech/status/master/favicon.png
  faviconSvg: https://raw.githubusercontent.com/imagix-tech/status/master/favicon.svg
  cname: status.imagix.tech
  theme: night
  css: ":root{ --up-border-left-color: #4cffaa; --down-border-left-color: #eb8799; } article.up { border-left: 0.7rem solid; } article.down { border-left: 0.7rem solid; }"
  logoUrl: https://raw.githubusercontent.com/imagix-tech/status/master/imagix.svg
  name: Status Page
  introTitle: "**Welcome** to the services Status Page"
  introMessage: Please, visit this page whenever you want to check the status of IMAGIX services and apps. Here we will also publish information about **scheduled maintenance**.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/imagix-tech
i18n:
  footer: IMAGIX
